name: city_pulse
description: Crowdsourced Civic Issue Reporting App

publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter_map_marker_popup: ^8.1.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  image_picker: ^0.8.7+4
  dio: ^5.9.0
  flutter_map: ^8.2.1
  latlong2: ^0.9.1
  table_calendar: ^3.0.9
  geolocator: ^14.0.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/  # include this if you have any images
